### ISSUE TITLE
ES6模块化支持

### ISSUE THREAD

**Issue by kfeng0806** [jabbany/CommentCoreLibrary#100]
请问是否准备加入ES6的module export支持? 能通过模块引入就太棒了

**Comment by jabbany** [comment]
有的有的。
去年初开始有这个计划，但是一直很难实现。当时的模块目标是支持 AMD, UMD 和 CommonJS 可以用于 React 或者 Angular。不过当时 TS 的编译器很辣鸡，加上这个项目采用了大量TypeScript 早期的模块系统（不是基于 import 的），所以过渡一直很麻烦。

我打算参考一下这个：
https://medium.com/ag-grid/understand-packaging-for-javascript-typescript-commonjs-and-everything-else-1fe835f3243a

不过目前需要：
- 把 CommentManager 和 Filter 之类的搬到 TypeScript
- 把模块都从 TS 换成 ES6 import
- 搞明白模板

**Comment by jabbany** [comment]
TS重构进程在 #103 进行管理～
