### ISSUE TITLE
请问一下定位弹幕里的motion这个参数值如何设定啊？查看文档并没有给出样例。

### ISSUE THREAD

**Issue by niu0717** [jabbany/CommentCoreLibrary#105]
文档中说motion跟着的格式是数组形式的IMotion, 但这个IMotion的格式具体是啥样的呢？

**Comment by niu0717** [comment]
比如Mode7时，使用send方法移动一段距离，（直接设置，x,y,toX,toY没有生效），那么使用motion该怎么设置呢？

**Comment by jabbany** [comment]
相关文档在[这里](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentProperties.md#motion-%E5%AF%B9%E8%B1%A1)

> 每个关键帧对象是一个Object，可以有一系列属性（如 x, y, alpha 等等）。每个 属性由一个 Object 表示

例子：
````JSON
{
    "motion": [
        {
            "x": { "from": 0, "to": 100, "dur": 2000, "delay": 0},
            "y": { "from": 100, "to": 0, "dur": 1000, "delay": 500},
        },
        {
            "size": { "from": 25, "to": 50, "dur": 1000, "delay": 0}
        }
    ]
}
````

例子表示的动画操作：
- 关键帧 1 -- `0-2000ms`
    - x 坐标由 `0` 变到 `100`
    - y 坐标在前 `500ms` 保持为`100`，之后在`500-1500ms` 从 `100` 变到 `0`，在`1500-2000ms` 保持为`0`
- 关键帧 2 -- `2000-3000ms`
    - size 由 `25` 变到 `50`

**Comment by niu0717** [comment]
好的，谢谢
