### ISSUE TITLE
0.11.1 版本不包含css_class -> className 这个新属性。

### ISSUE THREAD

**Issue by HerokunTan** [jabbany/CommentCoreLibrary#114]
请问作者大大Comment新属性className会在下个版本出来么.

**Comment by jabbany** [comment]
啊，新一版会的。
目前一直在本地做全面TypeScript化，为API稳定化+`1.0`准备。

如果你在用npm或者类似的包管理器，想现在就引入这个版本，可以通过把 `version` 设定成 github 库地址来实现。参考 https://docs.npmjs.com/files/package.json#github-urls。

**Comment by HerokunTan** [comment]
感谢
