### ISSUE TITLE
20 - 高阶定位混合弹幕组 使用问题

### ISSUE THREAD

**Issue by Geekhyt** [jabbany/CommentCoreLibrary#116]
这个类型的弹幕可以使用吗？有相关demo么

**Comment by jabbany** [comment]
这个格式被新生代的 gas 弹幕取代了。相关的库参考：https://github.com/OpenDanmakuCommunity/gas

目前demo还没集成，但是gas格式引擎是work的。。。

**Comment by Geekhyt** [comment]
emm，我理解目前还不能实现图片+文字形式的弹幕是吧。。

**Comment by jabbany** [comment]
是可以的，只是不是通过这个库实现。

**Comment by Geekhyt** [comment]
是的，想请教一下，如果我想在Aliplayer中使用图片+文字形式的弹幕，要怎么操作呢？

**Comment by LJG-V** [comment]
那该如何实现呢？?

**Comment by LJG-V** [comment]
> 



> emm，我理解目前还不能实现图片+文字形式的弹幕是吧。。

你解决了这个问题嘛？？？

**Comment by jabbany** [comment]
参考 #130
