### ISSUE TITLE
这里面依赖 dom 么？其实是想问只是算法还是，微信小程序可以用么

### ISSUE THREAD

**Issue by LengYXin** [jabbany/CommentCoreLibrary#119]

**Comment by jabbany** [comment]
CCL需要真正HTML5环境才可以正确支持。

根据以前issue #70 微信内的浏览器是不符合HTML5标准的，所以八成是不能正确工作的。尤其是如果你需要盖在视频上面的话，所谓X5内核是没有办法在视频上面绘制任何元素的。不过欢迎借鉴CCL内相关排版和布局以及弹幕管理的代码，至于具体如何正确绘制弹幕这个就得你自己研究了。。。

只需要主要的排版相关代码的话，也可以参考 https://github.com/jabbany/totem-danmaku/ 这里就是CCL的核心排版代码，用来在Gtk环境下渲染弹幕。
