### ISSUE TITLE
【讨论】Velocity.js 声称能加速JS动画，是否能提升CCL的性能？

### ISSUE THREAD

**Issue by m13253** [jabbany/CommentCoreLibrary#13]
丢个文章吧，文章结尾有介绍。
《[CSS 和 JS 动画哪个更快](http://www.admin10000.com/document/4339.html)》

[julianshapiro/velocity](https://github.com/julianshapiro/velocity) 的简介是加速 JavaScript 动画，是不是真的能加速 JavaScript 动画呢？

不过我想 velocity.js 应该能自动开启硬件加速并且不需要因为 vendor prefix 而头疼了。

**Comment by jabbany** [comment]
状态更新+合并 Issue。以下是目前各个优化方案的优缺点和有待解决的问题。：
- 现 `dev-cssonly` 采用  CSS transition 动画可实现GPU加速的滚动弹幕。非滚动弹幕依然采取JS手动animate （未来可能考虑keyframe） keyframe 讨论合并到 CSS 优化上 #46。CSS模式依然存在大量加入弹幕会卡的问题。
- Canvas 需要解决测量文字高度，转 #26 （相关话题，测量 textHeight） 。另一些问题包括 3D变幻等，不过可以采取联合模式（高级弹幕用DOM）部分解决。复杂的3D什么的WebGL什么的，似乎有一个 Hozuki/Bulletproof 正在搞，打算静观一下

这条先close掉，新的非CSS3/Canvas的优化方法欢迎新开
