### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by csacx** [jabbany/CommentCoreLibrary#39]
如果视频时间跳跃很大，比如以秒计算，很多弹幕都不会显示。最好是有一个容错，就是弹幕不用跟时间对得很精准，例如第3秒开始，第2秒内被跳过的弹幕自动全部补发出了，最好还可以选择是1s检查一次，或者是0.1s。UP怎么看？

**Comment by jabbany** [comment]
这个是设计内的，在`time()`函数里面默认任何时间倒退或前进超过2秒即为大跳跃，放弃跳跃内弹幕。

这个用于避免用户向后拖动时间轴导致派发时间更新有巨大跨度而导致输出大量弹幕的bug（比如在视频开始时用户立刻跳到结尾会导致所有弹幕同时输出）。

未来这个默认时间差将可以设置。当然绝对时间轴（跳跃后不是空屏而是把应该在这个时间显示的弹幕显示在相应的位置）也是可以实现的，不过那样效率太低（因为要比对整个行进区间内已经在运行的弹幕和时间轴弹幕（潜在添加对象），而这个操作要在每次time更新时完成，效率略低。如果在做个性化部署，解决的策略可以考虑override掉time函数。

**Comment by csacx** [comment]
不好意思，我没看代码:)我是成功嵌入了一个flash播放器，然后用这个flash播放器解析优酷土豆腾讯还有度盘的视频。在视频上面盖一层弹幕层。感觉还可以，就是视频卡出翔，还有部分弹幕消失。可惜现在的视频站都是用flash播放器，JS动不了它，如果他们像YouTube一样用H5，那应该就可以将弹幕层盖在他们的视频上了。

**Comment by jabbany** [comment]
flash播放器的话可以考虑在浏览器端模拟时间函数，然后通过flash的JS调用来给浏览器不定期同步播放时间（同时在播放暂停时触发），这样做一个架空时间轴比从JS读取flash播放进度效率要高很多，也不会导致time() 函数被调用太少。

**Comment by csacx** [comment]
感谢回复&这么久了还在改进。现在已经不做这些，转战node写游戏。网站也死得差不多了。播放器有投入使用过一段时间，CMS用的是DISCUZ!，自己写几个个插件和一个flash播放器+CCL+一些在线视频破解方法。总体来说，CCL是很好的，没什么短板，短板还是视频方面，flash解析加载总是很慢。校内外用H5播放器又有视频加密问题，对了，直播还是可以的，可以利用RTFMP协议。。。CCL可能这方面用法已经被开发得差不多，大家还是转战其他吧，我也专心玩JS和C++了。另外：PHP是最好的语言，不服来战！

**Comment by jabbany** [comment]
（清理一下Issue这个好像应该关掉）
