### ISSUE TITLE
关于CM.init()中this.stage.style.perspective报错

### ISSUE THREAD

**Issue by dongdongcpk** [jabbany/CommentCoreLibrary#40]
我在前端使用了angular.js
在页面中我引入了代码像这样：
```html
<link href="css/style.min.css" rel="stylesheet">
<script type="text/javascript" src="js/CommentCoreLibrary.js"></script>
<script type="text/javascript" src="js/controllers/boardController.js"></script>
```
在boardController.js中，我使用了CommentManager：
```javascript
app.controller('boardController', ['$scope',
    function($scope) {
        var CM = new CommentManager($('#my-comment-stage'));
        CM.init();
        CM.start();
        window.CM = CM;
    }]);
```
然后在控制台中，执行：
```javascript
var danmaku = {
    "mode": 1,
    "text": "hello world",
    "stime": 0,
    "size": 25,
    "color": 0xff00ff,
    "dur": 10000
};
CM.send(danmaku);
```
报错如下图：
![bug](http://github.com/dongdongcpk/fenpupu/blob/master/public/img/bug-CCL.png)
我在CommentCoreLibrary.js中690行附近修改：
```javascript
    // this.stage = stageObject;
    this.stage = stageObject[0];
```
之后运行正常，但是我并不知道这是什么错误。
浏览器为chrome，平台64位win7

**Comment by jabbany** [comment]
你是不是在用jQuery的选择器函数....
jQuery的selector返回的总是对象序列而非单一的Dom元素。所以说正确的方法应该是类似`var CM = new CommentManager($('#my-comment-stage').get(0));`的感觉。

**Comment by dongdongcpk** [comment]
按你的方法确实成功了，但是并没有发现在哪里用了选择器函数，我的前端知识太弱了，再研究一下，谢谢你的回答！

**Comment by jabbany** [comment]
那个 `$(...)` 就是 jQuery选择器，jQuery选择器返回的是jQuery对象（一般是一组任意数量0～inf 的DOM元素被一个支持jQuery的类似数组的东西包裹起来）。CCL是设计为用于裸HTML+JS的，所以要把里面的dom元素先提取出来再交给CCL。你这个地方在用的id选择最多会产生1个结果，所以可以用`get` 提取出第一个。

**Comment by dongdongcpk** [comment]
再次表示感谢！
