### ISSUE TITLE
stime这个属性貌似并没什么用？是还没有实现这个api吗？

### ISSUE THREAD

**Issue by xiao-hu00** [jabbany/CommentCoreLibrary#44]
如题

**Comment by jabbany** [comment]
stime是弹幕的起始时间，用于决定什么时间弹幕进入屏幕。。。
这个对传统非实时弹幕还是很关键的= =

**Comment by xiao-hu00** [comment]
懂了，我做的非绝对实时，从服务器获取列表，设定stime值来排序显示，后来是用定时器来send列表解决。另外，发现在手机上弹幕有点卡，是手机（我用的5s）原因还是？有可能解决吗？（小白一只，嘿嘿）

**Comment by jabbany** [comment]
master分支上的代码主要专注于兼容性，好像在 iOS 上会稍卡一些。你可以试试 dev-cssonly 这个分支，采取CSS3动画来滚动弹幕，应该在移动设备上要好很多。。。（不过因为没广泛测试兼容性，可能有的浏览器下有BUG之类的。。。

**Comment by xiao-hu00** [comment]
已经试着换分支了，确实，在手机端表现更加良好了，非常感谢。。。。css3的bug，还没测试，目测安卓的低端机可能会有吧，待测中...
