### ISSUE TITLE
build/CommentCoreLibrary.js 中的 CommentManager.load/.insert 均不能使加载的条目进入显示

### ISSUE THREAD

**Issue by zorceta** [jabbany/CommentCoreLibrary#45]
根据现有的执行路径，`CommentManager.load/.insert` 加载的条目会进入 `commentManager.timeline`，而 `CommentManager.startTimer` 调用的是 `commentManager.runline`；且 `.timeline` 中的内容不能进入 `.runline`。

**Comment by jabbany** [comment]
这是设计内的，详细可参考[API](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentManager.md)。

简单说，`insert`,`load`,`remove`都是操作弹幕时间轴（timeline）的。弹幕时间轴内的弹幕会根据 `time(..)` 函数通报的现播放时间和弹幕自身的开始时间，依情况被“发送”到运行弹幕队列（runline）。

如果希望弹幕立刻运行，则要用 `send`，直接把弹幕加入运行队列。

**Comment by zorceta** [comment]
欸我没注意看说明……
把函数名的语义理解错了
添麻烦了，抱歉
