### ISSUE TITLE
[讨论]关于CSS滚动弹幕

### ISSUE THREAD

**Issue by WhiteBlue** [jabbany/CommentCoreLibrary#46]
目前branch里面是使用CSS transition移动弹幕，然而有根本停不下来的问题。假如使用CSS animation移动的话就可以用animation-play-state属性暂停/恢复弹幕，是否有可行性呢。

**Comment by jabbany** [comment]
印象里当年开始搞的时候是没有办法通过 JS 设置 @keyframe 的（除非向页面注入 CSS，不过那样有点堪忧）。现在似乎可以了，或许有实现可能。

目前 `dev-cssonly` 那个分支其实是可停的，通过一个总的 timer 来“追着”弹幕的“逻辑位置”，然后到该停的时候会删掉 transition，改成固定坐标，重新开始移动的时候就会重新计算一个 transition 进去。这样主要的性能消耗就是添加删除弹幕（DOM）和暂停/启动瞬间。运行中的时候效率应该是和 CSS animation 同样享受 GPU 优化的。

现在 CSS 缺点还是浏览器下支持不一样，而且都有自己的BUG。不过至少现在在逐渐成熟。

参考文章： https://blog.andyet.com/2015/07/17/generating-css-keyframe-animations-with-javascript/

**Comment by jabbany** [comment]
v0.11.0 CSS弹幕渲染将默认提供滚动弹幕支持！（虽然方法不是animation-play-state）于是本 Issue可以先关掉了，耶！

定位（mode=7）CSS弹幕之类的还需要进一步研发。。。。
