### ISSUE TITLE
拖动视频时间的弹幕有问题啊

### ISSUE THREAD

**Issue by ivanfjz** [jabbany/CommentCoreLibrary#49]
拖动视频播放到新的位子，一下子就会出来大量的弹幕。然后我又拖回视频原来播放的位子，弹幕又全部消失了.....这个需要怎么配置，还是BUG？
我现在的timeupdate时间绑定了time()函数。还需要其他额外的配置吗？
```` js
media.addEventListener('timeupdate', function(e) {
                    CM.time(media.currentTime)
                });
```

**Comment by jabbany** [comment]
理论上拖动操作最好绑定一下 `clear()` 清掉屏幕上的弹幕。在ABPlayerHTML5 https://github.com/jabbany/ABPlayerHTML5/blob/master/src/js/ABPlayer.js#L506 这里处理了这个问题。

CCL自带的策略是：如果 `time` 获得的时间比目前时间早或晚2s或以上，则更新“上次update的时间“到time的时间，并不载入任何新的弹幕（也不去掉已经在运行的）。然后下个 `time()` 则会开始如平常一样的弹幕。否则视为普通的timeupdate，输出从上次到现在的区间内的弹幕。

**Comment by ivanfjz** [comment]
用clear()可以清楚大量弹幕的问题。
但是，如果视频再次托回到视频开始播放的时间，那么弹幕就不再显示了，这个怎么办？（比如：视频开始的时候，我就直接将视频拖到5分钟处，然后我再拖回来，那么从开始到5分钟这段时间内的弹幕就不显示了，5分钟后面的弹幕是正常的）

**Comment by jabbany** [comment]
hmm，你是指从0-5min之间的都不会再显示么？这个感觉不应该啊，往回seek按理说依然会更新视频位置的。如果确实不显示的话，应该是bug。

http://jabbany.me/ABPlayerHTML5/build/# 好像就没有这个问题？你可以测试一下看看。不过不知道其它部分代码所以不好说到底怎么导致的= =|||

**Comment by ivanfjz** [comment]
问题解决了，BUG的原因是我传递了视频的“秒”到CM.time()中导致的，把“秒”换成“微妙”就没有问题了，唉......文档没看仔细，SORRY

**Comment by jabbany** [comment]
OK
