### ISSUE TITLE
手机上h5版弹幕无法播放的问题有什么办法可以解决吗？

### ISSUE THREAD

**Issue by whstudy** [jabbany/CommentCoreLibrary#53]

**Comment by Catofes** [comment]
chrome 可以用的。

**Comment by whstudy** [comment]
IOS好像不行

**Comment by Catofes** [comment]
当年我试过ipad的safari貌似可以。最近就不知道了


white <notifications@github.com>于2016年3月26日周六 下午12:15写道：

**Comment by whstudy** [comment]
iPhone之前试过，不行

**Comment by jabbany** [comment]
CommentCoreLibrary只是负责纯弹幕层渲染。。。如果是指视频上不能挂弹幕层，那个属于播放器的问题（比如ABPlayerHTML5），是不属于CCL讨论范围的 = =|||
