### ISSUE TITLE
load 和 insert

### ISSUE THREAD

**Issue by aliencyl7** [jabbany/CommentCoreLibrary#54]
增加弹幕是通过insert 方法吗？insert 和 load 有什么区别？我通过insert 增加了弹幕，timeline是有弹幕，但runline 里一直没有

**Comment by jabbany** [comment]
insert是把弹幕插入timeline里面，load是清空timeline重载。如果insert 的弹幕比现在播放时间要早（或者一样）只会在重播的时候出现。。。
一个办法是把stime设的稍微晚一点（晚于目前的播放时间），另外就是，在insert后手动send一下强行加到runline里面。
