### ISSUE TITLE
似乎是BUG：播放器从上次历史位置开始播放，弹幕就出问题了

### ISSUE THREAD

**Issue by ivanfjz** [jabbany/CommentCoreLibrary#55]
大致情况就是：播放器从历史记录位置开始播放，那么弹幕会把历史记录位置之前的弹幕一次性全部刷新出来（ABPlayerHtml5这个也有同样的问题）

具体重现的逻辑过程：
在video的loadedmetadata事件中读取上次播放位置，然后将video.currentTime手动设置为上次播放时间。然后点击开始播放(触发CM.start())，弹幕就会把时间点之前的弹幕全部刷出来了，刷完之后，弹幕就恢复正常....

**Comment by ivanfjz** [comment]
补充下，还有种情况也会出现上面所说的情况：播放器未开始播放的时候，手动将播放时间调整到一个播放位置，然后再点击播放，那么这个播放位置之前的弹幕也会全部刷屏出来，刷完之后弹幕恢复正常情况（ABPlayerHtml5也有同样的问题，官方DEMO里那个就有）

**Comment by jabbany** [comment]
是的这个确实是个bug，目前正在研究怎么解决最靠谱。

这个主要是因为CCL的双时间轴设计，time()负责把弹幕从时间轴扔到运行队列里面，于是两次调用time时间跨度太大就会出现弹幕堆积状况。包括如果stop()之后还在调用time()然后再start()也有这个问题。

现在解决方法一是可以在移动时间轴时候clear掉运行队列（不过这个可能影响用户体验），也可以修正运行队列让弹幕使用绝对时间位置显示（这样会导致非常低性能的机器出现弹幕在屏幕中间产生的问题）。

**Comment by jabbany** [comment]
zacyu/bilibili-helper/issues/146

**Comment by ivanfjz** [comment]
我找到问题的原因：
```javascript
CommentManager.prototype.time = function(time){
		time = time - 1;
		if(this.position >= this.timeline.length || Math.abs(this.lastPos - time) >= 2000){
			this.seek(time);
			this.lastPos = time;
			if(this.timeline.length <= this.position) {
				return;
			}
		}else{
			this.lastPos = time;
		}
		for(;this.position < this.timeline.length;this.position++){
			if(this.timeline[this.position]['stime']<=time){
				if(this.options.limit > 0 && this.runline.length > this.limiter) {
					continue; // Skip comments but still move the position pointer
				} else if(this.validate(this.timeline[this.position])){
					this.send(this.timeline[this.position]);
				}
			}else{
				break;
			}
		}
	};

```
关键在于其中的
```
Math.abs(this.lastPos - time)
```
理论上当我面跳转时间的时候，当跳转时间的大于上次位置超过2秒，就要在时间队列timeline中通过seek()重新定位position，然后输出弹幕。正常播放的时候，通过time跳转是可以正常显示对应的弹幕。
然而如果当我们第一次调用time的时候，time值大于0，**由于 lastPos没有初始化，其值是undefined**，上面这个计算结果是NaN，这样子判断始终是false，这样子就导致了time函数没有去到时间队列timeline中去寻找对应的position，而默认position为0，结果是把弹幕从0到指定时间内的全部输出了。

解决方法：
方法很简单就是在CommentManager对象中初始化lastPos。
```
this.lastPos=0;
```
这样子就基本解决了BUG了.....但是，由于网络的问题，有时候触发了timeupdate事件时候，弹幕的时间队列却还没有填充完全（ajax异步获取弹幕加载，极有可能会出现这样的情况），那么也会出现这个BUG问题。解决方法就是监听CM 的load事件。待该事件触发后，再绑定video的timeupdate事件,以及其他的一些事件
```
CM.addEventListener('load',function(){
     media.addEventListener('timeupdate',function(){
            CM.time(Math.floor(media.currentTime*1000));
    });

   //其他事件绑定
})
```
