### ISSUE TITLE
runtimeFilter被注释掉的原因?

### ISSUE THREAD

**Issue by Kroderia** [jabbany/CommentCoreLibrary#57]
CommentCoreLibrary/src/CommentCanvasLibrary.js, line 154

**Comment by jabbany** [comment]
因为当时实验Canvas做底层导致运行方式换了，于是就关了不兼容的filter系统。

这个CommentCanvasLibrary没记错的话是不参与编译的，只是一直没有去掉因为还打算参考里面的一些码。
