### ISSUE TITLE
不知改变CCLOptions中属性类型是否可以

### ISSUE THREAD

**Issue by dbFlower** [jabbany/CommentCoreLibrary#59]
src/core/Core.d.ts line 30
`className:  string;`
更改为
`className:  any;`
是否会对其他地方产生影响？

**Comment by jabbany** [comment]
理论上感觉是可以的
但是感觉目前的用法并不支持非string类型的className值。。。。

**Comment by dbFlower** [comment]
OK,  我想在className 上加上比如弹幕类型、颜色等数据。 所以想把className换成function

**Comment by jabbany** [comment]
更新：
新版dev-new-loader中这些操作主要由 CommentFactory 处理所以应该不建议改变className的类型。
