### ISSUE TITLE
使用定位弹幕，无法渐变

### ISSUE THREAD

**Issue by mumu1993** [jabbany/CommentCoreLibrary#62]
danmaku.insert({
            mode: 7,
            x:80,
            y:0,
            stime: parseInt(time*1000),
            text:  gift_bullet(entry,head),
            dur:   1800,
            motion: [0,1]
        });

这样设置无效，无渐变效果

**Comment by mumu1993** [comment]
还有就是可不可以一个弹幕舞台设置两种互不遮挡的弹幕类型，一种滚动，一种在顶端显示，不让滚动弹幕遮挡顶部，有没有可以设置的参数呢？

**Comment by jabbany** [comment]
感觉上面代码有很多类型问题啊，比如 `parseInt(time * 100)`。。。不过言归正传，设置渐变的话并不是在motion里面。。。需要给出单独的Alpha渐变的属性（这个可以参考 Parser 是怎么解的）
```
 if(tmp != null && tmp.length>1){
  var alphaFrom = parseFloat(tmp[0]);
  var alphaTo = parseFloat(tmp[1]);
  obj.opacity = alphaFrom;
  if(alphaFrom !== alphaTo){
    obj.alpha = {from:alphaFrom, to:alphaTo}
  }
}
```
然后自己设置 obj.alpha的渐变就可以了

**Comment by jabbany** [comment]
不太懂互不遮挡的意思？如果弹幕足够多总会出现冲突。有下面两个实现：

1. 把顶部/滚动的的CommentSpaceAllocator的setBounds都设为全部高度的一定比例。这样如果出现冲突，会是同一个allocator里面冲突。效果是轨道不重叠，设立保留区。
2. 另一种方式是把顶部的/底部弹幕也加到滚动的SpaceAllocator里面，这样滚动弹幕就会尽可能避免使用已经被使用的轨道。（在固定弹幕消失后可以从SpaceAllocator中去掉）

这些只是改变了弹幕遮挡时的遮挡方式而已。。。如果需要一种弹幕永远在另一种上面，可以开单独的stage和manager。。。

**Comment by mumu1993** [comment]
舞台问题解决了，渐变能不能给段详细的代码呢？

**Comment by mumu1993** [comment]
if(tmp != null && tmp.length>1){
                var alphaFrom = parseFloat(tmp[0]);
                var alphaTo = parseFloat(tmp[1]);
                danmaku_gift.opacity = alphaFrom;
                if(alphaFrom !== alphaTo){
                    danmaku_gift.alpha = {from:alphaFrom, to:alphaTo}
                }
            }

**Comment by mumu1993** [comment]
没效果啊

**Comment by jabbany** [comment]
````
cm.send({
    mode:4,
    text:"Foo",
    alpha:{from:1, to:0},
    dur: 4000
})
````
这样的。渐变需要给出dur（总生存时间）要不然渐变不知道渐变多久。。。

**Comment by mumu1993** [comment]
渐显实现了，渐隐呢？

**Comment by jabbany** [comment]
这个全看你的from和to取值啊。。。

**Comment by mumu1993** [comment]
只能两个值吗？我说的意思是渐显渐隐 弹幕出来和消失都有动画的

**Comment by mumu1993** [comment]
就是0-1-0

**Comment by jabbany** [comment]
只能取一个渐变方向。如果需要复杂的动画模式就要使用Mode7弹幕，代码弹幕或者自己加一个解析类型了，普通的顶部底部弹幕模式并不支持这个。。。这个并不是CCL的限制（CoreComment是可以实现的）但是标准弹幕格式里面没有提供支持的问题

**Comment by mumu1993** [comment]
想自定义个弹幕动画，从左下角逐渐放大然后最后从上划出屏幕，期间要渐显-渐隐，求思路，谢谢

**Comment by mumu1993** [comment]
@jabbany 求个解，给点思路，谢谢啦

**Comment by jabbany** [comment]
我觉得实现这个的比较简单的方法是基于`CoreComment`在`update()`上做手脚。这个可以参考`ScrollComment`。最简单的是overload一下`update`这个函数然后通过读取 `ttl`和`dur`确定动画播放到的时刻，然后根据时刻确定属性的取值。这个完全可以参考 `ScrollComment`里面的类似实现。

简单的情况下可以设计一个 `size` 和 `x` 对于时间的函数，比如`x = (ttl/dur) * (width + stageWidth) - width`之类的然后比如 `size = S - k(ttl - dur/2)^2` 这种。

当然，如果还希望这些弹幕能互相避开的话，还得写一个新的CommentSpaceAllocator来解决撞击问题（目前的CommentSpaceAllocator认为弹幕高度不会变，所以排版的时候根据情况不同可能会把弹幕放太高（有空白）或者太低（有重合）。

需要注意的是这样没有硬件加速， 希望基于CSS加速的话就可以参考 `dev-cssonly`

**Comment by mumu1993** [comment]
用高阶定位混合弹幕组不能搞定吗？

**Comment by jabbany** [comment]
效果不好。。。高级弹幕没法根据舞台宽度自动调整所以除非如果弹幕舞台大小不变要不然就会有bug。。。

**Comment by mumu1993** [comment]
function send_bullet(entry,head){
        if (!danmaku) { return; }
        danmaku.insert({
            mode:  1,
            stime: (entry.play_time * 1000) + (1000 * Math.random()),
            text:  html_bullet(entry,head),
            dur:   life_bullet(entry),
        });
    }
    function send_git_bullet(entry,head,time) {
        if (!danmaku_gift) { return; }
        danmaku_gift.insert({
            mode: 7,
            stime: time*1000,
            x:10,
            y:0,
            text:  gift_bullet(entry,head),
            dur:   2000,
            alpha:{from:0, to:1},
        });
    }


可我现在是分两个弹幕舞台的啊，直接update不会对另一个有影响吗？

**Comment by mumu1993** [comment]
能加个QQ什么的么？？

**Comment by jabbany** [comment]
不太懂你说的意思但是用高级弹幕问题是不知道舞台的大小，这个跟有几个舞台没有关系。至于具体实现最好参考文档/引用一些已有的模式作为参考。我觉得比较简单，方便理解又靠谱的方法就是我之前上面说的，不过当然这不是唯一的办法。至于怎么实现都要根据你自己的需求进行开发。

另外，我并不用QQ。如果有什么文档上解释不清楚或者对CCL的一些内部做法不清楚的，欢迎直接在issues里面题问。不过，具体需求的开发和个例情况代码的调试我实在是帮不上的...

**Comment by mumu1993** [comment]
文档在哪里说的这个啊，找不到啊。。。

**Comment by jabbany** [comment]
如何扩展comment object以实现新的弹幕渲染模式参考comment object的定义。在docs里面有。具体怎么实现你要的功能这个需要你自己想。我在上面已经给出了我的想法，剩下的就是你自己研究一下什么实现适合你的需求。

**Comment by mumu1993** [comment]
我定了个mode为100的类，然后把源码改了，判断了一下mode100 走GiftComment这个方法，可是

`
var GiftComment = (function (_super) {

    var a;

    __extends(a, _super);

    function a(parent, data) {
        _super.call(this, parent, data);
        this.dur *= this.parent.options.scroll.scale;
        this.ttl *= this.parent.options.scroll.scale;
    }

    Object.defineProperty(a.prototype, "alpha", {
        set: function (a) {
            this._alpha = a;
            this.dom.style.opacity = Math.min(Math.min(this._alpha, this.parent.options.global.opacity), this.parent.options.scroll.opacity) + "";
        },
        enumerable: true,
        configurable: true
    });

    a.prototype.init = function (recycle) {
        if (recycle === void 0) { recycle = null; }
        _super.prototype.init.call(this, recycle);
        this.x = this.parent.width;
        if (this.parent.options.scroll.opacity < 1) {
            this.alpha = this._alpha;
        }
        this.absolute = true;
    };
    a.prototype.update = function () {
        console.log(22222)
        this.x = (this.ttl / this.dur) * (this.parent.width + this.width) - this.width;
    };

    return a;

}(CoreComment));
`

我这样写了一个方法，可是update连打印都不打印啊 。。。

**Comment by jabbany** [comment]
这种情况比较复杂因为每个用法都不一样，具体情况我也没法帮你，你得自己调试。

我个人觉得调试的入手点是看看comment的time有没有被call。如果没有的话应该是在CommentManager上做的有问题。我觉得最好的办法是仔细研究一下现在 ScrollComment 实现是怎么工作的然后试图去照着目前这个模式类推制作一个。
