### ISSUE TITLE
文件是否已经无效

### ISSUE THREAD

**Issue by dbFlower** [jabbany/CommentCoreLibrary#64]
`./src/core/CommentCoreLibrary.ts` 已经很久没有更新过了。 而且 `gruntfille.coffee` 也并没有引用该文件， 引用的是 `./src/CommentCoreLibrary.js`。 `./src/core/CommentCoreLibrary.ts` 是否应该移除掉？

**Comment by jabbany** [comment]
这个是未来用来替代 `src/CommentCoreLibrary.js` 的，但是因为还没能完全在TypeScript下实现原来JS里面的功能所以现在还在用没有换过去。换过去之前还要解决 IComment 类需要有一个Factory，然后得推敲一下API，所以有点慢。
