### ISSUE TITLE
普通弹幕有几秒延迟， stime和time()是设成一样的。

### ISSUE THREAD

**Issue by wmlgl** [jabbany/CommentCoreLibrary#68]
rt

**Comment by wmlgl** [comment]
配置了options.scroll.scale后会出现延时

**Comment by jabbany** [comment]
没有懂你说的延迟是什么意思？是指弹幕出现时间和stime不同么？那个的话是根据调用 time 的频率决定的。每次调用time会一起发送从上次调用到这次调用之间的弹幕。

**Comment by jabbany** [comment]
感觉好久没有回应就先关掉这个ticket了。还有问题的话可以重新打开。
