### ISSUE TITLE
CCL跟微信，手机QQ浏览器兼容性问题

### ISSUE THREAD

**Issue by zxkane** [jabbany/CommentCoreLibrary#70]
在微信或手机QQ浏览器中打开[demo](http://jabbany.github.io/CommentCoreLibrary/demo/)，在播放一段视频的时候，弹幕显示不出来。也可直接访问[这个精简的demo](https://jsfiddle.net/v78d5ubg/30/)。

调试后发现弹幕是正确显示了，但是video始终在弹幕的div上面，挡住了弹幕。貌似是弹幕div/video的CSS问题，粗略的调试了下，由于CSS非我所长，未找到解决方法。

**Comment by jabbany** [comment]
我试了一下可以看到啊。。。不过有一个问题是你没有 `cm.init()` 所以弹幕都没有空间布局。
可以参考 https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/Intro.md 这个和 这里 https://github.com/jabbany/CommentCoreLibrary/tree/master/demo/intro 的代码。

**Comment by zxkane** [comment]
用的iPhone上微信？它是基于Safari的Webkit，应该没有问题。我指的是基于X5内核的浏览器，iOS上重现需要独立安装的QQ浏览器。

刚才逛了下X5的论坛，问题应该是X5不遵守Html5规范，自己乱搞出来的问题。

[这个](http://bbs.mb.qq.com/thread-1505720-1-1.html), [这个](http://bbs.mb.qq.com/thread-286733-1-1.html)等等一堆开发者的抱怨。

**Comment by jabbany** [comment]
X5的问题就没办法了，只能联系他们解决。CCL是按照遵守HTML5协议的浏览器设计的。所以比如iPhone上的Safari上就不能用（iPad可以），因为iPhone的Safari接管了video元素强行全屏播放。

之前有人提议把Video通过Canvas播放参考（https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/HTML-canvas-guide/PuttingVideoonCanvas/PuttingVideoonCanvas.html）。就是使用canvas放视频信息，这样就可以绕开使用video元素。这个在iOS手机版也是不可用的，因为如文档2里面写的，这个API没有开放。目前我看这个可能 X5 估计也不支持。那样的话就没办法了。

**Comment by zxkane** [comment]
确实。腾讯这种搞法就是靠垄断走IE的老路了。

最新的Safari 10+已经支持video的`playsinline`可以页面内播放了。

**Comment by shenfusheng** [comment]
ie9不支持吗

**Comment by dbFlower** [comment]
在最新的 `CommentProvider` 中使用了promise。
若想使用 `CommentProvider`， 请先引用polyfill   https://github.com/jakearchibald/es6-promise

**Comment by shenfusheng** [comment]
不是报promise的错误，在ie9中没有报错，打开调试工具看到弹幕没有插入到舞台中![image](https://user-images.githubusercontent.com/9476838/31984505-645c6cdc-b994-11e7-8d93-4dc3ace9e1d3.png)，用ie10模拟就可以用
![image](https://user-images.githubusercontent.com/9476838/31984538-7c30628c-b994-11e7-8088-a752ea0e0efa.png)，看源码是用appendChild插入的，这个在ie应该是没问题的，主要是没报错看不出问题在哪里？

**Comment by dbFlower** [comment]
引用的CCL的版本是最新的吗？ 用什么形式加载的弹幕？具体代码片段可以看看吗

**Comment by shenfusheng** [comment]
我用的是github上下载的这个压缩包里面的官方实例
![image](https://user-images.githubusercontent.com/9476838/31985258-13103806-b997-11e7-8ff4-9cf77681efd3.png)，这边先点击载入弹幕，再点击启动
![image](https://user-images.githubusercontent.com/9476838/31985336-4e0354c0-b997-11e7-95e2-fe9379430537.png)
，用ie浏览器模拟ie10没问题，成功加载弹幕并显示，用ie浏览器模拟ie9再次同样的操作，则没有载入弹幕也没有报错，你有时间可以帮忙测下。用ie9打开这个官方实例http://jabbany.github.io/CommentCoreLibrary/demo/，是报promise的错误，还有刚才你说的这个库es6-promise，直接引入页面就可以了吗，还是需要初始化？说明文档好像没说要初始化。

**Comment by dbFlower** [comment]
我这里的IE9可以正确载入弹幕，如果还有新的问题请开新的issue。 
可能是IE偶尔抽风了
