### ISSUE TITLE
如果弹幕中有emoji表情的话如果去解决这个显示的问题

### ISSUE THREAD

**Issue by semi-xi** [jabbany/CommentCoreLibrary#71]
我刚才试了一下，如果是“\\u1f415” 那样在mac或者手机都会正常显示，但是在弹幕里面就变成了这个"ὁ5"

有什么好的办法去解决这个吗

**Comment by jabbany** [comment]
emoji不是标准编码区的，所以很容易bug。。。感觉是编码问题或者字体问题？（编码的话最好检查一下文件编码和传输都在用UTF-8）

字体的话，CCL默认字体是“黑体”，我没专门试过是不是Emoji可以显示，但是出于字体创造时间的考虑应该是不能显示的。一半这样会回退到平台有的字体，如果那个字体也不支持就不会显示。可以试试把 base.css
 里面的 font-family 尾部加上一个 EmojiSymbols 这样的字体来抓 emoji？

我现在用的Linux Mint下也看不到这个 emoji （除非提供一个支持这个的字体），默认会显示成一个方块 ¯\_(ツ)_/¯。

**Comment by semi-xi** [comment]
@jabbany  主要是我在同一个页面直接用div或者什么标签写个emoji表情能显示出来，但是如果在弹幕List里面传的话就会gg了。
大概这样
```js
// 载入弹幕列表
var danmakuList = [
    {
        "mode":1,
        "text":"Hello World(\u1f415)",
        "stime":0,
        "size":25,
        "dur":7000,
        "color":16711680,
        "dom":document.createElement("span")
    }
];
CM.load(danmakuList);
```

如果是直接在html上这样
```html
<span id="face">\u1f415</span> 然后在mobile 或者mac都可以直接显示出来。。这才是最迷的
```

**Comment by jabbany** [comment]
你这个是 UTF16吧。。。那个是非法UTF16的表示方式，JS不认的。试试用 `String.fromCodePoint(0x1f415)`

**Comment by semi-xi** [comment]
@jabbany 
用了你的方法发现是可以的。但是我又去查了下，我发现JS是支持UTF-16编码。只是我的非法，如果改成这样就可以了
```js
console.log('\u{1F680}');
```
