### ISSUE TITLE
新版本更新后忘了发布？

### ISSUE THREAD

**Issue by aptx4869** [jabbany/CommentCoreLibrary#76]
主分支上已经是 `0.11.0` 了，但是 npm 和bower上现在依然是去年9月份的 `0.9.3`，是不是中间版本忘了 `npm publish` 和在github上加 release了……

**Comment by jabbany** [comment]
感觉还有一些bug就一直托着呢。。。

**Comment by jabbany** [comment]
嘛，先搞成 `0.11.0-rc.1`
