### ISSUE TITLE
设置同屏最大的显示弹幕数量没有效果

### ISSUE THREAD

**Issue by mrluos** [jabbany/CommentCoreLibrary#80]
设置同屏最大的显示弹幕数量没有效果，
CM.limiter=3
CM.options.limit=3 都设置了。。

CM.options.limit 和CM.limiter 区别是什么？

**Comment by jabbany** [comment]
啊，确实似乎真的有个bug在这里（不过两个都设的话应该是work的）

最早设计是 CM.limiter是一个灵活的机制（可以定义成函数），CM.options.limit 则是一个数字上限。。。不过计划中 CM.limiter 要被deprecate全都改成用 CM.options.limit。目前有点bug，部分代码两个都会检查。。。。

工作方式是这样，如果运行时弹幕“正在运行”列表中弹幕数量大于限制，新的弹幕将不会被显示（send）。这个只被 `time` 使用，不会影响直接通过 `send` 发送的弹幕。

**Comment by mrluos** [comment]
感谢，回馈！

今天测试的时候发现，同时设置CM.options.limit  和CM.limiter，并且CM.limiter设置为CM.options.limit -1的时候，同屏的数量就会保持在CM.options.limit设置的数量。

非常奇怪

**Comment by jabbany** [comment]
是。。。因为转型不是特别完整。。。所以有一些奇怪的代码回路。。。

**Comment by jabbany** [comment]
新的patch之后就直接用 `CM.options.limit` 就可以了。去掉了 `CM.limiter` 的残留代码。

**Comment by mrluos** [comment]
哇，好的。感谢分享。
