### ISSUE TITLE
给弹幕设置stime属性但是没生效怎么破

### ISSUE THREAD

**Issue by shenfusheng** [jabbany/CommentCoreLibrary#81]
两个弹幕，一个stime设置1000，另一个stime设置5000，期望的结果是两个弹幕不会同时出现，但结果是两个还是同时出现了

**Comment by jabbany** [comment]
这个问题。。。信息不够啊。具体描述一下你 **输入弹幕的格式** ， **发送弹幕的代码** ，还有具体 **看到的效果（截图？）** 。只是说这个。。。完全没法重现啊。。。

（另外，同时出现是指这两个弹幕会同屏幕看到还是说同时开始运行。。。？

**Comment by shenfusheng** [comment]
![tim 20171012101128](https://user-images.githubusercontent.com/9476838/31475896-f9e672ca-af35-11e7-8699-d74a86289273.png)
![tim 20171012101240](https://user-images.githubusercontent.com/9476838/31475897-fa171970-af35-11e7-9a6e-970b61f3d435.png)
这是我本地运行的demo，当我调用start()方法时，我期望的结果是一个弹幕1s后出现，一个4s后出现，但是现在两个弹幕是同时出现了，求大神指点，第一次用这个框架，另外建议大神能不能开个qq群，方便讨论技术问题

**Comment by jabbany** [comment]
。。。。最好看一下[入门文档](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/Tutorial.zh_CN.md)。。。

直接调用 `send()` 是无视`stime`直接运行的（插入运行列表）。。。想用stime需要用 `insert` 插入弹幕列表，然后靠`time`具体进行派发。。。
