### ISSUE TITLE
请问如何屏蔽部分弹幕，调用remove方法提示 CM.remove is not a function

### ISSUE THREAD

**Issue by shenfusheng** [jabbany/CommentCoreLibrary#82]
有个需求想要屏蔽滚动弹幕，底部弹幕，顶部弹幕还有彩色的弹幕，看了文档有个remove方法，我是这样调用的
![image](https://user-images.githubusercontent.com/9476838/32043557-aeb6c780-ba6d-11e7-8f9d-c998bb409d51.png)，但是提示
![image](https://user-images.githubusercontent.com/9476838/32043589-c1209568-ba6d-11e7-8992-342866a21ed2.png)，是我调用错了吗，能否具体说下remove方法的使用，建议文档给出对应的例子就更好了，谢谢！

**Comment by dbFlower** [comment]
请参阅 [过滤器文档](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentFilter.md) 以及 [弹幕类型文档](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentTypes.md)
``` js 
  // 过滤顶部
  cm.filter.allowTypes[5] = false
  // 过滤底部
  cm.filter.allowTypes[4] = false 
```

**Comment by shenfusheng** [comment]
谢谢，还有一个问题，我想屏蔽不是白色的弹幕，在自定义规则里面这样子写有问题吗，没生效，也没报错
![image](https://user-images.githubusercontent.com/9476838/32046833-b71382ca-ba76-11e7-87c1-f74a476b83d1.png)，能否再帮忙给个例子，谢谢了，自己试了很久没试出来。

**Comment by dbFlower** [comment]
use 
``` javascript
cm.filter.addRule({
  subject: 'color',
  op: '=',
  value: 16777215,
  mode: 'accept'
})
```

**Comment by shenfusheng** [comment]
好的，非常感谢，value要传字符串类型才可以了。
