### ISSUE TITLE
如何动态改变弹幕字号大小

### ISSUE THREAD

**Issue by shenfusheng** [jabbany/CommentCoreLibrary#83]
我找到的方式是设置options.global.className，通过添加特定的class来设置字号大小，但是感觉有点麻烦，特别是当我需要设置20种文字大小，就要写好多css来控制，有没有更方便的方法？

**Comment by dbFlower** [comment]
请参阅 [CommentObject.md](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentObject.md)  可以指定每个 `cmt` 的字体大小

**Comment by jabbany** [comment]
弹幕字号是通过[弹幕抽象对象](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentProperties.md)里面设置size实现的。每条弹幕都有自己的大小参数，在load列表或者insert/send的时候给出字号就可以了。

如果在用CommentProvider，现有的格式都支持大小，如果有别的格式需要在客户端决定大小的，可以写一个新的格式parser。

如果需要动态（弹幕发射前）改大小，可以在CommentFilter里面用addModifier 加上一个修正函数（类似上方回复）来改变大小（具体可以看相关文档）。

**Comment by shenfusheng** [comment]
@dbFlower 用你说的监听beforeEnterComment设置字体大小，要在什么时候调用，我在insert和load前后调用都没效果

**Comment by jabbany** [comment]
。。。因为没有这个event。。。。（

**Comment by shenfusheng** [comment]
原来是enterComment，被坑了

**Comment by jabbany** [comment]
那个就是第三种，要注意的是不会触发重新规划弹幕路径，所以那样排版可能会出问题。

**Comment by dbFlower** [comment]
@jabbany  @shenfusheng  抱歉两位， 那个事件是我后来自己加上去的。 
加在了 [L213](https://github.com/jabbany/CommentCoreLibrary/blob/6ec5d55e824c577e743c45f4439ce734c1d92697/src/CommentManager.js#L213) 之前

```
  this.dispatchEvent("beforeEnterComment", cmt);
```
 
我觉得需要有这个钩子来处理一些事情而不是通过 `filter` 来添加 modifier 。

非常抱歉。

**Comment by shenfusheng** [comment]
我发现一个问题，用enterComment来设置弹幕字体大小的时候，如果当前时间段没有弹幕的时候，设置后，当过几秒弹幕出现时大小并没有改变，另外通过 filter用addModifier 的方法不是用来过滤弹幕的吗，怎么设置弹幕还请大神具体代码演示一下，非常感谢！

**Comment by jabbany** [comment]
嗯，标准库里面没有这个event。标准库里面event设计只是通知事件发生（或者允许探知中途object），在event hook里面改变对象状态影响运行是违反event的协约的（因为异步。。。所以收到event的时候理论上对象可能已经被操作了等等，当然目前dispatchEvent实现是同步的）

不过首先，实现这个“加上字号”，正确的方法应该是在load的时候就给出完整的弹幕对象。当然，如果希望可以允许用户override信息的话，最好的做法是这样：

```Javascript
...
CM.init();
var OVERRIDE_SIZE = 20;
...
CM.filter.addModifier(function (commentData) {
    var newOverriddenData = {};
    for (var key in commentData) {
        if (key == 'size') {
            newOverriddenData['size'] = OVERRIDE_SIZE;
            continue;
        }
        newOverriddenData[key] = commentData[key];
    }
    return newOverriddenData;
});
```

这么做的好处是，不会更改`timeline`里面的`commentData`对象。这样，比如原始弹幕是50的size，这么覆盖之后，如果想取消覆盖，直接去掉modifier就可以了。如果使用了上面的方法，那timeline里面原来的大小就被覆盖成了这个新的大小。

**Comment by jabbany** [comment]
啊这个也有一阵了，就先关掉。还有什么问题的话，欢迎重新打开。
