### ISSUE TITLE
想要实现单条弹幕的停止怎么做

### ISSUE THREAD

**Issue by yshmore** [jabbany/CommentCoreLibrary#84]
看了下CoreComment.prototype.stop的实现是空

**Comment by jabbany** [comment]
对的，`CoreComment`和其子类的`stop()`并不保证能单独停止弹幕，因为不同的后端实现有不同的停止需求（如果是基于主event timer，比如定位动画，由于共享timer所以不能设计单独停止。如果是基于CSS动画则这个会按照预期工作）。

如果需要可停止的定位弹幕，最好的方法是创造新的子类，然后实现这个函数。CoreComment是动画弹幕，其位置由ttl和dur决定。所以停止的方法是创造一个flag让 time 函数有时无视其输入。

**Comment by jabbany** [comment]
hmm，看起来没有回复就先关掉这个了。如果有问题欢迎再开。
