### ISSUE TITLE
弹幕管理器有没有show/hide方法

### ISSUE THREAD

**Issue by coolicer** [jabbany/CommentCoreLibrary#86]
扫了一眼api，似乎没有，只看到start,stop,clear ..

**Comment by jabbany** [comment]
并没有这两个方法啊，一直都没有。不知道你看的是哪个文档？[这里](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentManager.md)是弹幕管理器的文档。

**Comment by coolicer** [comment]
我之前是用另外的库。我后面再研究你这个吧

**Comment by jabbany** [comment]
好吧。。。不过为什么在这个库上开issue？

**Comment by jabbany** [comment]
BTW 如果需要全局隐藏弹幕的话，直接在stop之后把弹幕容器的 css 设成 `visibility:hidden` 就可以了。。。由于是容器上的东西所以都是在管理器之外的

**Comment by coolicer** [comment]
@jabbany stop后应该不会插入DOM了吧

**Comment by jabbany** [comment]
不是。。。stop是停止目前已经在舞台的弹幕移动。。。time负责根据播放时间把弹幕从弹幕列表放到舞台上。

不过如果只是为了隐藏弹幕，两个都可以不做，这样取消隐藏时看到的是目前正在运行的弹幕而不是空白屏幕。

**Comment by coolicer** [comment]
不是很懂，后期有需要再研究源码，谢谢了。
