### ISSUE TITLE
直播弹幕重叠问题

### ISSUE THREAD

**Issue by uje** [jabbany/CommentCoreLibrary#89]
直播弹幕重叠问题使用了send方法，如何实现不重叠？

**Comment by uje** [comment]
代码在这里，你看下

**Comment by jabbany** [comment]
看着没问题啊。同屏超过一定数量的话肯定就重叠了。。。这肯定没办法啊。。。你现在每个弹幕高80px整个stage也放不下几条弹幕，肯定是要重叠的啊

**Comment by dbFlower** [comment]
这么搞肯定会重叠啊， 直播弹幕密度这么大的情况下可以考虑只显示部分了

**Comment by uje** [comment]
但是像虎牙那些弹幕也很多弹幕，看起来也没重叠啊

**Comment by uje** [comment]
@jabbany 弹幕多的时候能否做队列，而不是实时展示？

**Comment by dbFlower** [comment]
@uje  做成队列更爆炸， 你可以考虑不展示所有弹幕， 筛选掉一些重复的弹幕。

**Comment by jabbany** [comment]
队列更爆炸是真的，同屏只能显示一定数目的弹幕，这个物理约束是没办法的。

几个绕开同屏弹幕很多的办法：
- 把弹幕字体变小，间距变小（比如你jsfiddle里面把line-height, height从css里面去掉就会好很多）
- 限制同屏弹幕上限：用弹幕stage高度/平均单条高度 = “平均轨道数”。然后根据弹幕平均长度可以算出理想情况下满屏最多多少条，用limiter设置上限就可以。这个docs里面有
- 合并相似/相同弹幕（参考楼上，这个只能预处理，新来的直播弹幕参考一下runline里面有没有类似的弹幕来决定send不send）

CCL可以支持密度比较大的弹幕，参考demo里面的Test 6。比这个再多就真的比较困难了，不管用什么样的布局算法都会有困难

**Comment by uje** [comment]
好的，谢谢。我之前尝试过加队列，然后发现，同样长度的弹幕能够整齐排列不重叠，但是不同长度的弹幕就会出现重叠，因为动画用的是css3，动画时长固定，速率就会因长度而改变。

**Comment by jabbany** [comment]
嗯，设计上就是这样的固定时长弹幕（大部分站点都是这样的，可以避免发一条特别长的弹幕导致一直被刷屏）
目前排布算法为了兼容性不是用的完美排布。这个可以参考issues里面有另一个，可以通过改空间规划器里面的一行实现无重叠规划（不过就是会牺牲一点效率）

**Comment by jabbany** [comment]
先把这个关掉。还有问题的话欢迎重新打开。

**Comment by jabbany** [comment]
未来参考用：同类issue #77
