### ISSUE TITLE
修复教程文件里面的 CSS 资源位置

### ISSUE THREAD

**Issue by baobin81** [jabbany/CommentCoreLibrary#90]

**Comment by jabbany** [comment]
？水平滚动效果？

**Comment by baobin81** [comment]
window.addEventListener("load", function(){
	function $(element){
	// 获取 DOM 对象的短写，如果你在用 jQuery 也可以采用类似的方法
	return document.getElementById(element);
};
	var CM = new CommentManager(document.getElementById('my-comment-stage'));
	CM.init('canvas'); // 初始化
	CM.isRunning=true;
	CM.start();
	
	// 载入弹幕列表
	var danmakuList = [
		{
			"mode":1,
			"text":"test1",
			"stime":0,
			"size":25,
			"color":0xfffff
		}
	];
	CM.load(danmakuList);

	// 插入弹幕test2

	var someDanmakuAObj = {
		"mode":1,
		"text":"test2",
		"stime":200,
		"size":30,
		"color":0xff0000

	};
	CM.insert(someDanmakuAObj);
	

});

**Comment by baobin81** [comment]
![image](https://user-images.githubusercontent.com/12002754/40460818-2cb993de-5f3b-11e8-9176-c6c9e661927d.png)
没有看到任何效果

**Comment by baobin81** [comment]
不知道谁，愿不愿加QQ 协助我，实现一些想法

**Comment by jabbany** [comment]
哦你是在看 `demo/tutorial/`。。。那个好像CSS链接跪了。。。

**Comment by baobin81** [comment]
去的QQ号是：2464754978

**Comment by baobin81** [comment]
![image](https://user-images.githubusercontent.com/12002754/40461035-0568ae86-5f3c-11e8-913d-340236b1a9d2.png)
我在理解，这个案例

**Comment by jabbany** [comment]
我并没有 QQ。。。。

**Comment by baobin81** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>实验</title>
	<meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="x-ua-compatible" content="IE=edge" />
	<style>
		@-ms-viewport { width:device-width; }
		@media only screen and (min-device-width:800px) { html { overflow:hidden; } }
		html { height:100%; }
		body { height:100%; overflow:hidden; margin:0; padding:0; font-family:Arial, Helvetica, sans-serif; font-size:16px; color:#FFFFFF; background-color:#000000; }
		.myabp{
			position:absolute;
			left: 0px;
			top: 10px;
			width: 100%;
			height: 50px;
			z-index: 1000;
		}
	</style>


<link rel="stylesheet" href="js/style.css" />
<script src="js/CommentCoreLibrary.js"></script>
</head>
<body >
	<div id='my-player' class='myabp'>
		<div id='my-comment-stage' class='container'></div>
	</div>

</body>
</html>
<script>
window.addEventListener("load", function(){
	function $(element){
	// 获取 DOM 对象的短写，如果你在用 jQuery 也可以采用类似的方法
	return document.getElementById(element);
};
	var CM = new CommentManager(document.getElementById('my-comment-stage'));
	CM.init('canvas'); // 初始化
	CM.isRunning=true;
	CM.start();
	
	// 载入弹幕列表
	var danmakuList = [
		{
			"mode":1,
			"text":"test1",
			"stime":0,
			"size":25,
			"color":0xfffff
		}
	];
	CM.load(danmakuList);

	// 插入弹幕test2

	var someDanmakuAObj = {
		"mode":1,
		"text":"test2",
		"stime":200,
		"size":30,
		"color":0xff0000

	};
	CM.insert(someDanmakuAObj);
	

});
</script>

麻烦谁帮看看，这个代码，为什么看不到弹幕

**Comment by baobin81** [comment]
![image](https://user-images.githubusercontent.com/12002754/40461396-d28a90d6-5f3d-11e8-9b17-d96fd4171d11.png)
![image](https://user-images.githubusercontent.com/12002754/40461407-dc10a398-5f3d-11e8-8858-eb9e52eba916.png)

**Comment by jabbany** [comment]
你这没有推动时间轴肯定是没有弹幕的。。。
