### ISSUE TITLE
av39444 mode9 大量报错

### ISSUE THREAD

**Issue by xjbeta** [jabbany/CommentCoreLibrary#97]
![](https://i.loli.net/2018/11/04/5bde7cb428c72.png)

[av39444](https://www.bilibili.com/video/av39444)
[av39444.xml](https://gist.github.com/xjbeta/bc4be05ad36b8a7dd19637bfb7385782)

**Comment by jabbany** [comment]
mode 9应该是新的代码弹幕 （https://github.com/Bilibili/bas ）。由于官方未开源实现，也并没有许可第三方反向工程他们的实现（参考上面的库里面的相关issue），CCL原生是并不支持mode9的。

不过你可以自己引入他们的码，然后参考现在scripting engine的实现在comment factory里面加入相关绑定来bind mode9，应该就可以支持了。由于这样不被bilibili目前的许可支持，所以我们不能加入现在的CCL代码里面。

**Comment by xjbeta** [comment]
主要应为会卡住时间更新
导致本来能正常显示的弹幕也无法显示
`cm.filter.allowTypes[9] = false;`
屏蔽掉mode 9  解决

**Comment by jabbany** [comment]
另一个解决方法是设置
`cm.filter.allowUnknownTypes = false`
来屏蔽掉所有CCL不支持的弹幕mode
