### ISSUE TITLE
图片定位弹幕mode 17可以使用吗

### ISSUE THREAD

**Issue by sunlongjian** [jabbany/CommentCoreLibrary#98]
你好，问题如标题

**Comment by jabbany** [comment]
一直没人用所以就没设计格式的定义。。。
理论上实现起来图片弹幕并不难，有具体需求的话欢迎在这里讨论一下希望的实现会是什么样。

**Comment by apppleKey** [comment]
怎么实现，好期待，因为可能有这个需求

**Comment by LJG-V** [comment]
> 一直没人用所以就没设计格式的定义。。。 理论上实现起来图片弹幕并不难，有具体需求的话欢迎在这里讨论一下希望的实现会是什么样。

这个问题加上了嘛?

**Comment by jabbany** [comment]
实现弹幕内嵌各种内容（图片，文字，链接，等等）都可参考 #130 的方法：更改 CoreComment 的 constructor 和 init 方法，在init的时候往dom里面加东西即可。
