### ISSUE TITLE
讨论弹幕暂停几秒后再次播放的方案

### ISSUE THREAD

**Issue by lynxerzhang** [jabbany/CommentCoreLibrary#99]
比如一个弹幕从右到左匀速运动，当前使用的是库里面的CssScrollComment，现在我需要修改下，因为需求是运动到屏幕中央停止几秒，然后再继续运动，想了下最好使用css来解决，目前找到了animation 属性，animation可以直接写入弹幕dom的内联样式里面，但是对应keyframes不行。

现在的方案是动态创建一个style标签放入document中，然后每次弹幕出现，动态创建对应的keyframes标签放入这个style中，那么这个style标签中的keyframes会越来越多。

问题：这样会对性能产生影响吗？我现在的想法是每个动画结束后，通过css的deleteRule api把对应的keyframes删除，这样避免style标签中的keyframes越来越多。

**Comment by jabbany** [comment]
好神奇的需求。。。感觉还是用JS比较灵活，毕竟弹幕到达终点还要去掉，这个加上暂停相关操作比较不好管理。。。

我记得当年有一个神级通用的css可以自适应任何弹幕，然后只要通过调整父级paused属性就可以，但是现在找不到了。。。

**Comment by lynxerzhang** [comment]
感谢回复！我现在在尝试通过css的animation属性配合css keyframes试试，如果可以源代码改的也少。我是在您的项目代码基础上改的，所以能直接css最好了
